<link rel="stylesheet" href="{{ asset('back-end/dist/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('back-end/dist/css/font_awesome_5_free.min.css') }}">
<link rel="stylesheet" href="{{ asset('back-end/dist/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('back-end/dist/css/bootstrap-datepicker.min.css') }}">
<link rel="stylesheet" href="{{ asset('back-end/dist/css/bootstrap-timepicker.min.css') }}">
<link rel="stylesheet" href="{{ asset('back-end/dist/css/bootstrap-tagsinput.css') }}">
<link rel="stylesheet" href="{{ asset('back-end/dist/css/duotone-dark.css') }}">
<link rel="stylesheet" href="{{ asset('back-end/dist/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('back-end/dist/css/iziToast.min.css') }}">
<link rel="stylesheet" href="{{ asset('back-end/dist/css/fontawesome-iconpicker.min.css') }}">
<link rel="stylesheet" href="{{ asset('back-end/dist/css/bootstrap4-toggle.min.css') }}">
<link rel="stylesheet" href="{{ asset('back-end/dist/css/summernote-bs4.css') }}">
<link rel="stylesheet" href="{{ asset('back-end/dist/css/style.css') }}">
<link rel="stylesheet" href="{{ asset('back-end/dist/css/components.css') }}">
<link rel="stylesheet" href="{{ asset('back-end/dist/css/spacing.css') }}">
<link rel="stylesheet" href="{{ asset('back-end/dist/css/custom.css') }}">